### ISSUE TITLE
Disable hotkey on context

### ISSUE THREAD

**Issue by trajano** [Perlence/AutoHotkey.py#16]
I am trying to set it so my mouse side buttons revert back to the default values when Overwatch is in front.  But this does not appear to work
```
def is_overwatch():
    return ahk.visible_windows.get_active().process_name == "Overwatch.exe"

overwatch_ctx = ahk.HotkeyContext(is_overwatch)
overwatch_ctx.hotkey("XButton2").disable()
overwatch_ctx.hotkey("XButton1").disable()
```

I also tried also no luck
```
overwatch_ctx.hotkey("XButton2", lambda hotkey: hotkey.disable())
overwatch_ctx.hotkey("XButton1", lambda hotkey: hotkey.disable())
```

I also tried
```
overwatch_ctx.hotkey("XButton2", ahk.send("XButton2"))
overwatch_ctx.hotkey("XButton1", ahk.send("XButton1"))
```

**Comment by trajano** [comment]
This finally worked, but it still means that AHK is sending the button
```
overwatch_ctx = ahk.HotkeyContext(is_overwatch)
overwatch_ctx.hotkey("XButton2", lambda : ahk.send("{XButton2}"))
overwatch_ctx.hotkey("XButton1", lambda : ahk.send("{XButton1}"))
```

rather than letting the OS handle

**Comment by Perlence** [comment]
Another option is creating a "non-Overwatch" context for your XButton1 and XButton2 hotkeys.

```python
non_overwatch_ctx = ahk.inactive_window_context(exe="Overwatch.exe")
non_overwatch_ctx.hotkey("XButton1", ...)  # Your regular hotkey
non_overwatch_ctx.hotkey("XButton2", ...)
```

**Comment by trajano** [comment]
> Another option is creating a "non-Overwatch" context for your XButton1 and XButton2 hotkeys.

The problem with that approach is I have to do that for every sort of do an "and" since it's not just Overwatch that may be doing FPS.

**Comment by Perlence** [comment]
Here's yet another option, using the `~` [modifier](https://www.autohotkey.com/docs/v1/Hotkeys.htm#Tilde):

```python
overwatch_ctx = ahk.active_window_context(exe="Overwatch.exe")
overwatch_ctx.hotkey("~XButton1", lambda: None)
overwatch_ctx.hotkey("~XButton2", lambda: None)
```

It makes the buttons do their default action, overriding the global hotkey, and I think it passes through the original event.

**Comment by Perlence** [comment]
I don't think any changes are needed in AutoHotkey.py, so I'll close it.
