### ISSUE TITLE
How do I hold-on the key

### ISSUE THREAD

**Issue by moonlovestar** [Perlence/AutoHotkey.py#7]
Hi guys,

    Anyone knows that how do I do the same as below AHK script?

    // Click F7 to hold-on Alt for 1 sec before release
    F7::
    Send {Alt down}
    Sleep 1000
    Send {Alt up}

Regards,
Wayne

**Comment by Perlence** [comment]
Hey Wayne, you could do the following:

```python
import ahkpy

@ahkpy.hotkey("F7")
def hold_alt():
    ahkpy.send("{Alt down}")
    ahkpy.sleep(1)
    ahkpy.send("{Alt up}")
```

**Comment by moonlovestar** [comment]
Thanks a lot!

I try to test your script (i.e., below script) and click F7 to start it, but it only send one "1" to my Notepad.
I expected output should be 1111111111111111111111, not a single 1.

Any idea for this?

@ahkpy.hotkey("F7")
def hold_alt():
    ahkpy.send("{1 down}")
    ahkpy.sleep(5)
    ahkpy.send("{1 up}")

**Comment by Perlence** [comment]
If your goal is to have a hotkey that sends the <kbd>1</kbd> key 22 times, then this show do it:

```python
@ahkpy.hotkey("F7")
def hold_alt():
    ahkpy.send("{1 22}")
```

**Comment by moonlovestar** [comment]
> If your goal is to have a hotkey that sends the 1 key 22 times, then this show do it:
> 
> ```python
> @ahkpy.hotkey("F7")
> def hold_alt():
>     ahkpy.send("{1 22}")
> ```

Actually no.
Just curious why the {1 down} has different behavior as hold-on 1 by my finger.  :)

It should not be the issue though, we can close the issue.

Regards,
Wayne

**Comment by Perlence** [comment]
Right, I'm not sure why AHK behaves this way 🙂
